In [5]:
price=list()
age=list()
fuel=list()



f=open("toyota1.csv","r")
data=f.readline()
while(True):

  data=f.readline()
  if not data:
    break;
  print(data)
  temp=data.split(",")
  price.append(int(temp[0]))
  age.append(int(temp[1]))
  fuel.append(temp[3])

13500,23,46986,Diesel,90,1165

13750,23,72937,Diesel,90,1165

13950,24,41711,Diesel,90,1165

14950,26,48000,Diesel,90,1165

13750,30,38500,Diesel,90,1170

12950,32,61000,Diesel,90,1170

16900,27,4522,Diesel,56,1245

18600,30,75889,Diesel,90,1245

21500,27,19700,Petrol,192,1185

12950,23,71138,Diesel,43,1105

20950,25,31461,Petrol,192,1185

19950,22,43610,Petrol,192,1185

19600,25,32189,Petrol,192,1185

21500,31,23000,Petrol,192,1185

22500,32,34131,Petrol,192,1185

22000,28,18739,Petrol,56,1185

22750,30,34000,Petrol,192,1185

17950,24,21716,Petrol,110,1105

16750,24,25563,Petrol,110,1065

16950,30,64359,Petrol,110,1105

15950,30,67660,Petrol,110,1105

16950,29,43905,Petrol,110,1170

15950,28,56349,Petrol,110,1120

16950,28,32220,Petrol,110,1120

16250,29,25813,Petrol,110,1120

15950,25,28450,Petrol,110,1120

17495,27,34545,Diesel,110,1120

15750,29,41415,Petrol,110,1120

16950,28,44142,Petrol,110,1120

In [9]:
print(price,"\n\n")

print("Highest price of car is",max(price))

[13500, 13750, 13950, 14950, 13750, 12950, 16900, 18600, 21500, 12950, 20950, 19950, 19600, 21500, 22500, 22000, 22750, 17950, 16750, 16950, 15950, 16950, 15950, 16950, 16250, 15950, 17495, 15750, 16950]


Highest price of car is 22750

In [17]:
print(price)
print(age,"\n\n")

print("Age of car having lowest price is",age[price.index(min(price))])

[13500, 13750, 13950, 14950, 13750, 12950, 16900, 18600, 21500, 12950, 20950, 19950, 19600, 21500, 22500, 22000, 22750, 17950, 16750, 16950, 15950, 16950, 15950, 16950, 16250, 15950, 17495, 15750, 16950]
[23, 23, 24, 26, 30, 32, 27, 30, 27, 23, 25, 22, 25, 31, 32, 28, 30, 24, 24, 30, 30, 29, 28, 28, 29, 25, 27, 29, 28]


Age of car having lowest price is 32

In [18]:
print("Lowest price of car is",min(price))

Lowest price of car is 12950

In [20]:
print("Average price of car is",sum(price)/len(price))

Average price of car is 17306.724137931036

In [24]:
print(fuel,"\n\n")
frequency ={}
for car in fuel:
  if car in frequency:
    frequency[car]+=1
  else:
    frequency[car]=1
print(frequency,"\n\n")

['Diesel', 'Diesel', 'Diesel', 'Diesel', 'Diesel', 'Diesel', 'Diesel', 'Diesel', 'Petrol', 'Diesel', 'Petrol', 'Petrol', 'Petrol', 'Petrol', 'Petrol', 'Petrol', 'Petrol', 'Petrol', 'Petrol', 'Petrol', 'Petrol', 'Petrol', 'Petrol', 'Petrol', 'Petrol', 'Petrol', 'Diesel', 'Petrol', 'Petrol']


{'Diesel': 10, 'Petrol': 19}